### ISSUE TITLE
Set points being converted to fahrenheit when not needed

### ISSUE THREAD

**Issue by joshtbernstein** [cgarwood/homeassistant-zwave_mqtt#128]
- Home Assistant version: 0.109.3
- ozwdaemon version or add-on version: 1.0.15
- homeassistant-zwave_mqtt version: 14 (and master also)

I just switched to a Honeywell T6 zwave climate device and the set points are being converted to fahrenheit when the values reported already are. When I have the cooling set point at 76F, HA shows 168.8F (76C converted to F). It looks like the values reported by the climate devices are in fahrenheit, however the units label is set to celsius, so the values get "converted". The builtin zwave integration does not have this issue.

[mqtt.dump.txt](https://github.com/cgarwood/homeassistant-zwave_mqtt/files/4581559/mqtt.dump.txt)

**Comment by marcelveldt** [comment]
@Fishwaldo do you mind taking a look at this ?
I believe this is an issue in the daemon as I've spotted the same behaviour multiple times. 
Looks like Units is set to Fahrenheit sometimes while it should be Celcius...

See below for an example (this is on my own mesh)

<img width="1422" alt="Schermafbeelding 2020-05-11 om 19 34 29" src="https://user-images.githubusercontent.com/6389780/81592559-70936a80-93be-11ea-80c4-17b1aba25a28.png">

**Comment by Fishwaldo** [comment]
I think this should be fixed. Some testing would be great!

Note - Some of the attributes (such as Units, ValueSet, ValuePolled, ChangeVerified) can change any time, so you should always check them when getting a ValueChanged event.

**Comment by joshtbernstein** [comment]
Any specific way to test? Or just install this as usual.

**Comment by EnochPrime** [comment]
I have the same thermostat and am running:
- Home Assistant 0.109.6
- Z-Wave over MQTT (Pre-release) 0.0.15
- ozwdaemon 0.1.97

The issue still exists. My set point is 70F and it displays 158F in home assistant.

**Comment by marcelveldt** [comment]
@jdm12989 did you pull the latest version of the OZW Daemon in docker ?

**Comment by EnochPrime** [comment]
> @jdm12989 did you pull the latest version of the OZW Daemon in docker ?

I did it through Portainer using the latest tag so I'm trusting it actually did. From the logs:

> [20200514 14:24:51.818 UTC] [default] [info]: Staring  "ozwdaemon"  Version:  "0.1.97"
> [20200514 14:24:51.818 UTC] [default] [info]: OpenZWave Version:  "1.6.1123"
> [20200514 14:24:51.818 UTC] [default] [info]: QT-OpenZWave Version:  "1.0.0"
> [20200514 14:24:51.818 UTC] [default] [info]: QT Version:  5.12.5

**Comment by Fishwaldo** [comment]
That’s the latest. I’d need to see the logs from the docker container when it’s receiving those setpoint messages

**Comment by EnochPrime** [comment]
> That’s the latest. I’d need to see the logs from the docker container when it’s receiving those setpoint messages

@Fishwaldo It was initially set to 70F, I then changed it to 65F via the thermostat and then changed it again to 75F via Home Assistant.

> [20200514 14:25:05.541 UTC] [ozw.library] [debug]: Detail - Node: 11 Queuing (Query) ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x01, 0x25, 0x35, 0xbe
> [20200514 14:25:05.541 UTC] [ozw.library] [debug]: Detail - Node: 11 Queuing (Query) ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x07, 0x25, 0x36, 0xbb
> [20200514 14:25:52.258 UTC] [ozw.library] [info]: Info - Node: 11 Sending (Query) message (Callback ID=0x35, Expected Reply=0x04) - ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x01, 0x25, 0x35, 0xbe
> [20200514 14:25:53.705 UTC] [ozw.library] [info]: Info - Node: 11 Received thermostat setpoint report: Setpoint Heating 1 = 70.0F
> [20200514 14:25:53.707 UTC] [ozw.library] [info]: Info - Node: 11 Sending (Query) message (Callback ID=0x36, Expected Reply=0x04) - ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x07, 0x25, 0x36, 0xbb
> [20200514 15:51:37.144 UTC] [ozw.library] [info]: Info - Node: 11 Received thermostat setpoint report: Setpoint Heating 1 = 65.0F
> [20200514 15:53:01.210 UTC] [ozw.library] [debug]: Detail - Node: 11 Queuing (Send) ThermostatSetpointCmd_Set (Node=11): 0x01, 0x0f, 0x00, 0x13, 0x0b, 0x08, 0x43, 0x01, 0x01, 0xcc, 0x01, 0x6c, 0x83, 0xf9, 0x25, 0x54, 0x09
> [20200514 15:53:01.210 UTC] [ozw.library] [debug]: Detail - Node: 11 Queuing (Send) ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x01, 0x25, 0x55, 0xde
> [20200514 15:53:01.211 UTC] [ozw.library] [info]: Info - Node: 11 Sending (Send) message (Callback ID=0x54, Expected Reply=0x13) - ThermostatSetpointCmd_Set (Node=11): 0x01, 0x0f, 0x00, 0x13, 0x0b, 0x08, 0x43, 0x01, 0x01, 0xcc, 0x01, 0x6c, 0x83, 0xf9, 0x25, 0x54, 0x09
> [20200514 15:53:02.479 UTC] [ozw.library] [info]: Info - Node: 11 Sending (Send) message (Callback ID=0x55, Expected Reply=0x04) - ThermostatSetpointCmd_Get (Node=11): 0x01, 0x0a, 0x00, 0x13, 0x0b, 0x03, 0x43, 0x02, 0x01, 0x25, 0x55, 0xde
> [20200514 15:53:02.536 UTC] [ozw.library] [info]: Info - Node: 11 Received thermostat setpoint report: Setpoint Heating 1 = 40.0F

**Comment by Fishwaldo** [comment]
are you filtering the log files? cause there should be a ton more info there.

**Comment by EnochPrime** [comment]
@Fishwaldo ... yup sorry, lets try this again.

This appears to be the full section for changing from 70F to 65F via device:
https://pastebin.com/TEqLNPjN

And this is for changing from 65F to 75F via Home Assistant:
https://pastebin.com/rifphV59

**Comment by EnochPrime** [comment]
@Fishwaldo and @marcelveldt I believe I may know the cause now. I left my setup running for a while and just noticed that the set point temperature is displaying correctly now. When it changed to the correct value is when the current temperature change from 70F to 71F.

Looking at the code the units parameter is only set when the function "update_current_temp" runs. As this function is run by the init and I have had a current temperature displayed then device_unit must have been None on the first pass.

**Comment by joshtbernstein** [comment]
@jdm12989 How long did you have to wait for that? I've had my running for a few hours and it's still not correct.

I'd really like to move over to this, but can't because of this issue.

**Comment by joshtbernstein** [comment]
Opened an issue in the HA Core repo since it looks like development has moved over there.
